FROM node:22-alpine
WORKDIR /app

# Install dependencies only when needed
COPY package.json package-lock.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the development server with hot reload
CMD ["npm", "run", "dev"]